#!/bin/bash
echo "Doing backup of line.rb..."
[ -f "line.rb" ] || (echo "line.rb not found. Did you choose correct directory?" && exit 1)
mv line.rb ../line.rb.backup
echo "Clearing directory"
rm -rf *.rb
echo "Restoring line.rb"
mv ../line.rb.backup ./line.rb
echo "Done"
