class Collmex::Api::Cmxmgd < Collmex::Api::Line
  SPECIFICATION =
  [
  { name: :typkennung, type: :string , const: "CMXMGD" },
  { name: :mitgliednummer, type: :integer },
  { name: :anrede, type: :string },
  { name: :titel, type: :string },
  { name: :vorname, type: :string },
  { name: :name, type: :string },
  { name: :firma, type: :string },
  { name: :abteilung, type: :string },
  { name: :straße, type: :string },
  { name: :plz, type: :string },
  { name: :ort, type: :string },
  { name: :reserviert, type: :string },
  { name: :reserviert, type: :string },
  { name: :land, type: :string },
  { name: :telefon, type: :string },
  { name: :telefax, type: :string },
  { name: :e_mail, type: :string },
  { name: :konto_nr, type: :string },
  { name: :blz, type: :string },
  { name: :iban, type: :string },
  { name: :bic, type: :string },
  { name: :bankname, type: :string },
  { name: :reserviert, type: :string },
  { name: :reserviert, type: :string },
  { name: :geburtsdatum, type: :date },
  { name: :eintrittsdatum, type: :date },
  { name: :austrittsdatum, type: :date },
  { name: :bemerkung, type: :string },
  { name: :telefon2, type: :string },
  { name: :skype_vo_ip, type: :string },
  { name: :inhaber, type: :string },
  { name: :ausgabemedium, type: :string },
  { name: :adressgruppe, type: :int_arr },
  { name: :zahlungsbedingung, type: :integer },
  { name: :abrechnung_ueber, type: :integer },
  { name: :ausgabe_sprache, type: :string },
  ]
end