# http://www.collmex.de/cgi-bin/cgi.exe?1005,1,help,daten_importieren_produkt

class Collmex::Api::Cmxprd < Collmex::Api::Line
  def self.specification
    [
      { name: :satzart, type: :string, const: "CMXPRD" },
      { name: :produktnummer, type: :string },
      { name: :bezeichnung, type: :string },
      { name: :bezeichnung_eng, type: :string },
      { name: :basismengeneinheit, type: :string },
      { name: :produktgruppe, type: :integer },
      { name: :firma, type: :integer },
      { name: :steuerklassifikation, type: :integer },
      { name: :gewicht, type: :integer },
      { name: :gewicht_mengeneinheit, type: :string },
      { name: :preismenge, type: :integer },
      { name: :produktart, type: :integer },
      { name: :inaktiv, type: :integer },
      { name: :preisgruppe, type: :integer },
      { name: :verkaufs_preis, type: :currency },
      { name: :ean, type: :string },
      { name: :hersteller, type: :string },
      { name: :versandgruppe, type: :integer },
      { name: :mindestbestand, type: :integer },
      { name: :bestellmenge, type: :integer },
      { name: :chargenpflicht, type: :integer },
      { name: :beschaffungsart, type: :integer },
      { name: :produktionsdauer, type: :integer },
      { name: :lohnkosten, type: :currency },
      { name: :lohnkosten_bezugsmenge, type: :integer },
      { name: :bemerkung, type: :string },
      { name: :kostenermittlung, type: :integer },
      { name: :kosten, type: :currency },
      { name: :bezugsmenge_kosten, type: :integer },
      { name: :ek_lieferant, type: :integer },
      { name: :ek_steuerklassifikation, type: :integer },
      { name: :ek_prod_nr_d_lieferanten, type: :string },
      { name: :ek_verpackungseinheit, type: :integer },
      { name: :ek_bezeichnung, type: :string },
      { name: :ek_preis, type: :currency },
      { name: :ek_preismenge, type: :integer },
      { name: :ek_lieferzeit, type: :integer },
      { name: :ek_waehrung, type: :string },
      { name: :reserviert, type: :integer },
      { name: :reserviert, type: :integer },
      { name: :webauftritt_nr, type: :integer },
      { name: :shop_kurztext, type: :string },
      { name: :shop_langtext, type: :string },
      { name: :texte_sind_html, type: :integer },
      { name: :dateiname, type: :string },
      { name: :keywords, type: :string },
      { name: :titel, type: :string },
      { name: :abweichendes_template_nr, type: :integer },
      { name: :bild_url, type: :string },
      { name: :grundpreis_menge_1, type: :integer },
      { name: :grundpreis_menge_2, type: :integer },
      { name: :grund_mengeneinheit, type: :integer },
      { name: :preis_auf_anfrage, type: :integer },
      { name: :inaktiv, type: :integer },
      { name: :shop_kategorien, type: :integer },
    ]
  end
end
